# Configuration file format reference:
# https://embarkstudios.github.io/cargo-about/cli/generate/config.html

targets = [
	"x86_64-unknown-linux-gnu",
	"aarch64-unknown-linux-gnu",
	"x86_64-pc-windows-msvc",
	"x86_64-apple-darwin",
	"aarch64-apple-darwin"
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = true
private = { ignore = true }

# Deserializing TOML documents with values here for use with the cargo-about crate API
# does not work because cargo-about expects borrowed strings. To avoid pinning build
# dependencies to older TOML parser versions, use a placeholder value instead
accepted = []
