preserve_hierarchy: true
commit_message: "[skip ci]"
pull_request_title: "[GUI] Localization files updates"
pull_request_labels:
  - l10n

files:
  - source: /packages/packsquash_gui/src/assets/i18n/en/*.ftl
    translation: /packages/packsquash_gui/src/assets/i18n/%two_letters_code%/%original_file_name%
