[package]
name = "packsquash_options"
description = "Configuration data structures for PackSquash"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_with = "3.0.0"
schemars = { workspace = true, features = ["derive", "enumset"] }
field_types = "1.1.0"

sysinfo = { version = "0.29.5", default-features = false }

ahash = { workspace = true, features = ["serde"] }
enumset = { workspace = true, features = ["serde"] }
globset.workspace = true
camino = { workspace = true, features = ["serde1"] }
const-default = { version = "1.0.0", features = ["derive"] }

[features]
# Support all kinds of files added by modifications by default
default = ["mod-support"]

# This feature will include support for all the mods that PackSquash will ever support
mod-support = ["optifine-support", "mtr3-support"]

optifine-support = []
mtr3-support = []

serializable-squash-options = []
