[package]
name = "packsquash_util"
description = "Miscellaneous, small utilities used by several parts of PackSquash"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_path_to_error = "0.1.11"
