name: Bug report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!

        Before submitting, please make sure that:
          - The topic does **not** involve a security vulnerability or a method to bypass the pack protection feature. The process for reporting such matters is covered under our [security policy](https://github.com/ComunidadAylas/PackSquash/security/policy), and it **never** involves initial disclosure on a public GitHub issue.
          - The problem is not related to PackSquash not being installed as described in the [installation guide](https://github.com/ComunidadAylas/PackSquash/wiki/Installation-guide).
          - If you are trying to use a pack in a Minecraft server, the pack works fine in singleplayer. If it works in singleplayer, a network or server misconfiguration may be the cause of the problem.
          - You can answer any issue-related questions that may be asked in the comments in a reasonable timeframe. Issues with missing information for developers tend to be unactionable, eventually closed, and a waste of time for everyone involved!
          - The report follows the guidelines for issues described in the [Contributing Guidelines](https://github.com/ComunidadAylas/PackSquash/blob/master/CONTRIBUTING.md#-issues).

        After your report is submitted, a repository maintainer will try to resolve it or get back to you as soon as possible.

  - type: dropdown
    id: distribution
    attributes:
      label: Distribution
      description: What flavor of PackSquash are you using?
      options:
        - Windows executable
        - Linux x64 executable
        - Linux x64 APT package
        - Linux ARM64/AArch64 executable
        - Linux ARM64/AArch64 APT package
        - Universal macOS executable
        - GitHub action
        - Unstable or custom build (please describe in the "Additional context" section)
        - Other (please describe in the "Additional context" section)
        - N/A (the distribution does not matter; please explain why if it's not obvious)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Type '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: attached-files
    attributes:
      label: Attached files
      description: If applicable, add pack files that help reproduce your problem.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other information that might be relevant to resolving the problem here.
