blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/bGUSamzJYp
    about: Get quicker support for small questions or matters that may not warrant opening an issue
