# Reference:
# https://appimage-builder.readthedocs.io/en/latest/reference/version_1.html

version: 1

script:
  # Clean up directories created by the recipe
  - rm "$TARGET_APPDIR" -rf || true
  - rm "$REPO_DIR" -rf || true
  # Create a temporary Debian repository folder to put the generated Debian
  # packages on, so we can install it like any other packages
  - mkdir -p "$REPO_DIR"
  - stat target/"${CARGO_BUILD_TARGET:-.}"/debian/packsquash-gui_*_${TARGET_APPIMAGE_APT_ARCH}.deb >/dev/null 2>&1 || packages/packsquash_gui/src-tauri/bundles/deb/build.sh
  - cp -f target/"${CARGO_BUILD_TARGET:-.}"/debian/packsquash-gui_*_${TARGET_APPIMAGE_APT_ARCH}.deb "$REPO_DIR"
  - command -v apt-ftparchive >/dev/null 2>&1 || { apt-get update && apt-get install -yq apt-utils; }
  - CWD="$PWD" && cd "$REPO_DIR" && apt-ftparchive packages . > Packages && cd "$CWD"
  # The following two commands are a workaround for the local APT package not
  # being saved to the archives directory, as expected by appimage-builder
  - mkdir -p appimage-build/apt/archives
  - cp -f target/"${CARGO_BUILD_TARGET:-.}"/debian/packsquash-gui_*_${TARGET_APPIMAGE_APT_ARCH}.deb appimage-build/apt/archives

AppDir:
  app_info:
    id: com.github.comunidadaylas.packsquash.gui
    name: PackSquash (GUI)
    icon: packsquash
    version: !ENV ${VERSION}
    exec: usr/bin/packsquash-gui

  apt:
    arch: !ENV ${TARGET_APPIMAGE_APT_ARCH}
    sources:
      # The key_url was hacked together from the recipe documentation examples
      # and the errors that showed up when it was absent. Maybe there is a
      # better way to get it?
      - sourceline: !ENV 'deb [arch=${TARGET_APPIMAGE_APT_ARCH}] https://deb.debian.org/debian/ bullseye main'
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x648ACFD622F3D138
      - sourceline: !ENV 'deb [arch=${TARGET_APPIMAGE_APT_ARCH}] https://deb.debian.org/debian-security/ bullseye-security main'
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x112695A0E562B32A
      - sourceline: !ENV 'deb [arch=${TARGET_APPIMAGE_APT_ARCH}] https://deb.debian.org/debian/ bullseye-updates main'
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x648ACFD622F3D138
      - sourceline: !ENV 'deb [trusted=yes] file:${REPO_DIR}/ ./'

    include:
      # Including our whole package is pretty elegant, isn't it? :)
      - packsquash-gui
      # This package is necessary to avoid this: https://github.com/AppImageCrafters/appimage-builder/pull/191
      - shared-mime-info

    exclude:
      - systemd
      - systemd-sysv
      - util-linux
      - util-linux-extra
      - xkb-data
      - fdisk
      - dmsetup
      - mount
      - dbus-daemon
      - perl-base
      - readline-common
      - libpam-modules
      - avahi-daemon
      - bubblewrap

  files:
    exclude:
      # Development, localization, documentation and configuration files
      - usr/include
      - usr/share/bug
      - usr/share/man
      - usr/share/doc
      - usr/share/doc-base
      - usr/share/lintian
      - usr/share/sounds
      - usr/share/bash-completion
      - usr/share/zsh
      - usr/share/applications
      - usr/share/pkgconfig
      - usr/share/pam
      - usr/share/pam-configs
      - usr/share/util-linux
      - usr/share/initramfs-tools
      - usr/share/locale
      - usr/lib/pkgconfig
      - etc
      - var
      # systemd, lsb, modprobe.d, udev and misc daemon files
      - lib/systemd
      - usr/lib/systemd
      - usr/lib/x86_64-linux-gnu/systemd
      - lib/udev
      - usr/lib/udev
      - lib/lsb
      - lib/modprobe.d
      - usr/lib/kernel
      - usr/share/systemd
      - usr/share/polkit-1
      - usr/lib/tmpfiles.d
      # Unneeded utility programs and libraries
      - usr/sbin
      # The only missing alphabet letter here is p, to not delete the PackSquash executable
      - usr/bin/{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,q,r,s,t,u,v,w,x,y,z}*
      - sbin
      - bin

  # Tests don't work due to Tauri security checks we can't work around:
  # https://github.com/tauri-apps/tauri/blob/35264b4c1801b381e0b867c1c35540f0fbb43365/core/tauri-utils/src/lib.rs#L202
  #test:
  #  debian-stretch:
  #    image: debian:stretch-slim
  #    command: ./AppRun

AppImage:
  arch: !ENV ${TARGET_APPIMAGE_ARCH}
  update-information: !ENV 'gh-releases-zsync|ComunidadAylas|PackSquash|latest|PackSquash (GUI)-*${TARGET_APPIMAGE_ARCH}.AppImage.zsync'
