[package]
name = "packsquash_gui"
description = "Minecraft resource and data pack optimizer (GUI)"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
packsquash.workspace = true
packsquash_options = { workspace = true, features = ["serializable-squash-options"] }

tauri = { version = "1.4.1", features = ["clipboard-write-text", "dialog-open", "dialog-save", "native-tls-vendored", "os-all", "shell-execute", "shell-open", "updater", "window-request-user-attention", "window-set-title"] }
tauri-plugin-store = { version = "0.0.0", git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

toml = { workspace = true, features = ["parse", "display"] }

log = { workspace = true, features = ["std"] }

path-absolutize = "3.1.0"

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

serde.workspace = true
serde_json.workspace = true
toml = { workspace = true, features = ["parse"] }

cargo-about = "0.5.6"
krates = "0.13.1"

[features]
# Enable Tauri production mode by default.
# This feature is managed by the Tauri CLI. On development mode,
# the crate is run with default features disabled
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

# Use cargo deb instead of the Tauri deb bundler because it is much more flexible.
# Tauri deb bundler source: https://github.com/tauri-apps/tauri/blob/62ce02f6b5e95b1bb9682cdce7e678350ad666d1/tooling/bundler/src/bundle/linux/debian.rs
[package.metadata.deb]
name = "packsquash-gui"
maintainer = "Alejandro González <me@alegon.dev>"
copyright = "PackSquash developers"
license-file = ["../../../LICENSE", "0"]
extended-description-file = "target/debian/extended_package_description.txt"
suggests = "packsquash"
assets = [
    ["target/release/packsquash_gui", "usr/bin/packsquash-gui", "755"],
    ["../../../README.md", "usr/share/doc/packsquash-gui/README.md", "644"],
    ["bundles/icons/256x256.png", "usr/share/icons/hicolor/256x256/apps/packsquash.png", "644"],
    ["bundles/deb/org.aylas.packsquash.gui.desktop", "usr/share/applications/", "644"]
]
section = "utils"
# For each release with the same version number (shouldn't be too many),
# increment this, and change APT repo action
revision = "0"
