# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.238.1/containers/rust/.devcontainer/base.Dockerfile

# [Choice] Debian OS version (use bullseye on local arm64/Apple Silicon): bullseye, bookworm, trixie
ARG VARIANT="trixie"
FROM mcr.microsoft.com/vscode/devcontainers/rust:1-${VARIANT}
